[mypy]
python_version = 3.12
strict = true
warn_unreachable = true
warn_unused_ignores = true
show_error_codes = true
namespace_packages = true
explicit_package_bases = true

[mypy-tests.*]
disallow_untyped_defs = false
